"""Integration tests: the real CLI end-to-end on the real Excels (5.6).

Runs ``python -m etl build|approve|release`` as subprocesses in the project
root and asserts exit codes plus produced artifacts. The final state left
behind (dashboard.html + data_log.csv) is the intended deliverable.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PYTHON = sys.executable

# Generated state shared with the real CLI when run from the project root.
STATE_FILES = ("dashboard.html", "payload.json", "data_log.csv")


def run_cli(*argv: str, cwd: Path | None = None) -> subprocess.CompletedProcess:
    env = dict(os.environ)
    env["PYTHONPATH"] = str(PROJECT_ROOT)  # `-m etl` works from any cwd
    return subprocess.run(
        [PYTHON, "-m", "etl", *argv],
        cwd=str(cwd or PROJECT_ROOT),
        env=env,
        capture_output=True,
        text=True,
        timeout=180,
    )


class TestCliIntegration(unittest.TestCase):
    def setUp(self):
        # Isolate each test from generated state left by previous runs
        # (the repo starts with no commits; state files are gitignored).
        self._backup = tempfile.TemporaryDirectory()
        self._moved: list[tuple[Path, Path]] = []
        for name in STATE_FILES:
            src = PROJECT_ROOT / name
            if src.exists():
                dst = Path(self._backup.name) / name
                shutil.move(str(src), str(dst))
                self._moved.append((src, dst))

    def tearDown(self):
        for src, dst in self._moved:
            if src.exists():  # leftover generated by this test
                src.unlink()
            shutil.move(str(dst), str(src))
        self._backup.cleanup()
    def test_full_build_approve_release_flow(self):
        with tempfile.TemporaryDirectory() as tmp:
            dest = Path(tmp) / "release"
            # build
            build = run_cli("build")
            self.assertEqual(build.returncode, 0, build.stderr)
            self.assertIn("[OK]", build.stdout)
            dashboard = PROJECT_ROOT / "dashboard.html"
            self.assertTrue(dashboard.exists())
            self.assertGreater(dashboard.stat().st_size, 100_000)  # vendored libs inlined
            # approve
            approve = run_cli("approve", "--approver", "CI Tester")
            self.assertEqual(approve.returncode, 0, approve.stderr)
            self.assertIn("Aprobación registrada", approve.stdout)
            # release
            release = run_cli("release", "--dest", str(dest))
            self.assertEqual(release.returncode, 0, release.stderr)
            self.assertTrue((dest / "dashboard.html").exists())
            self.assertIn("Publicado localmente", release.stdout)

    def test_rerun_invalidates_approval_at_cli_level(self):
        with tempfile.TemporaryDirectory() as tmp:
            # build + approve
            self.assertEqual(run_cli("build").returncode, 0)
            self.assertEqual(run_cli("approve", "--approver", "CI Tester").returncode, 0)
            # rebuild -> approval stale (R3)
            self.assertEqual(run_cli("build").returncode, 0)
            stale = run_cli("release", "--dest", str(tmp))
            self.assertNotEqual(stale.returncode, 0)
            self.assertIn("BLOQUEADO", stale.stderr)
            # fresh approval -> release ok
            self.assertEqual(run_cli("approve", "--approver", "CI Tester").returncode, 0)
            ok = run_cli("release", "--dest", str(tmp))
            self.assertEqual(ok.returncode, 0, ok.stderr)

    def test_release_without_approval_blocks(self):
        with tempfile.TemporaryDirectory() as tmp:
            self.assertEqual(run_cli("build").returncode, 0)
            blocked = run_cli("release", "--dest", str(tmp))
            self.assertNotEqual(blocked.returncode, 0)
            self.assertIn("BLOQUEADO", blocked.stderr)
            self.assertIn("R1", blocked.stderr)

    def test_build_blocks_on_tampered_data(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            shutil.copy2(PROJECT_ROOT / "Usuarios_Ventas_2026.xlsx", tmp_path / "usuarios.xlsx")
            shutil.copy2(PROJECT_ROOT / "Ventas_Productos_2026.xlsx", tmp_path / "ventas.xlsx")
            # Corrupt the ventas copy: drop half the rows -> match rate ~50%.
            import pandas as pd

            ventas = pd.read_excel(tmp_path / "ventas.xlsx", engine="openpyxl",
                                   dtype_backend="numpy_nullable")
            ventas.head(50).to_excel(tmp_path / "ventas_half.xlsx", index=False)
            blocked = run_cli("build", "--usuarios", "usuarios.xlsx",
                              "--ventas", "ventas_half.xlsx", cwd=tmp_path)
            self.assertNotEqual(blocked.returncode, 0)
            self.assertIn("BLOQUEADO", blocked.stderr)
            self.assertFalse((tmp_path / "dashboard.html").exists())
            self.assertTrue((tmp_path / "data_log.csv").exists())
            with open(tmp_path / "data_log.csv", encoding="utf-8") as fh:
                rows = [r for r in fh.read().strip().splitlines()]
            self.assertTrue(rows[-1].endswith("FAILED") or "FAILED" in rows[-1])


if __name__ == "__main__":
    unittest.main()